from enum import Enum


class Moves(Enum):
    BACK_ROTATE_CLOCKWISE = 0
    BACK_ROTATE_ANTICLOCKWISE = 6

    TOP_RIGHT = 1
    TOP_LEFT = 7

    LEFT_UP = 2
    LEFT_DOWN = 8

    RIGHT_UP = 3
    RIGHT_DOWN = 9

    BOTTOM_LEFT = 4
    BOTTOM_RIGHT = 10

    FRONT_ROTATE_CLOCKWISE = 5
    FRONT_ROTATE_ANTICLOCKWISE = 11
