from enum import IntEnum


class MovesN3(IntEnum):
    LEFT_UP = 0
    LEFT_DOWN = 6

    BOTTOM_LEFT = 1
    BOTTOM_RIGHT = 7

    FRONT_ROTATE_CLOCKWISE = 2
    FRONT_ROTATE_ANTICLOCKWISE = 8

    BACK_ROTATE_CLOCKWISE = 3
    BACK_ROTATE_ANTICLOCKWISE = 9

    TOP_RIGHT = 4
    TOP_LEFT = 10

    RIGHT_UP = 5
    RIGHT_DOWN = 11


# VERSION REDUCIDA PARA RUBIKS DE 2x2x2
class MovesN2(IntEnum):
    LEFT_UP = 0
    LEFT_DOWN = 6

    BOTTOM_LEFT = 1
    BOTTOM_RIGHT = 7

    FRONT_ROTATE_CLOCKWISE = 2
    FRONT_ROTATE_ANTICLOCKWISE = 8