[general_config]

exercise = latent_space_exercise
#Can be latent_space_exercise, even_numbers, guess_numbers, guess_numbers_game

load_backup_weights = False
#Can be True, False

with_adam = True
#Can be True, False

adaptative_learning_rate = True
#Can be True, False

noise = True #Este noise de true y false no interactua con el noise factor, si no quieren noise ponganlo en 0
noise_factor = 0.3

epochs = 250

learning_rate = 0.05
#Can be TANH, LOGISTICA, RELU

activation_function = LOGISTICA

latent_space_dim = 70


test_size = 0.7

beta = 1
