[general_config]

exercise = latent_space_exercise
#Can be latent_space_exercise, even_numbers, guess_numbers, guess_numbers_game

load_backup_weights = True
#Can be True, False

noise = False

epochs = 25000

learning_rate = 0.05
#Can be TANH, EXP, RELU

activation_function = EXP

test_size = 0.5

beta = 1
