[general_config]

exercise = latent_space_exercise, latent_plot
#Can be latent_space_exercise

load_backup_weights = False
#Can be True, False

with_adam = True
#Can be True, False

adaptative_learning_rate = False
#Can be True, False

noise = False #Este noise de true y false no interactua con el noise factor, si no quieren noise ponganlo en 0
noise_factor = 0

epochs = 2500

learning_rate = 0.05

#Can be TANH, LOGISTICA
activation_function = LOGISTICA

latent_space_dim = 2


test_size = 0
momentum_alpha = 0.3

beta = 1
