[general_config]
dataset = ./TP2-ej2-conjunto.csv
epochs = 5
learning_rate = 0.01

#Can be linaer;nolinear;step
classifier = linear

[step_classifier]
umbral = 0

[linear_classifier]

[nolinear_classifier]
activation_function = TANH
beta = 1.0


[normalization]