[general_config]
dataset = TP2/onelayer_network/TP2-ej2-conjunto.csv
epochs = 250
learning_rate = 0.01

#Can be linear, nolinear, step
classifier = nolinear

[step_classifier]
umbral = 0

[linear_classifier]

[nolinear_classifier]
#Can be TANH, EXP, RELU
activation_function = RELU
beta = 0.9


[normalization]