[general_config]
#Can be xor, even_numbers, guess_numbers, guess_numbers_game
exercise = guess_numbers_game
#Can be True, False
noise = True
epochs = 250
learning_rate = 0.05
#Can be TANH, LOGISTICA, RELU
activation_function = LOGISTICA
beta = 1
