from .font_graphs import plot_error_and_accuracy_changing_layers, plot_error_and_accuracy_changing_act_function, plot_error_and_accuracy_changing_momentum, plot_error_and_accuracy_changing_adam, plot_error_and_accuracy_changing_learning_rate, plot_error_and_accuracy_changing_noise_factor



if __name__ == "__main__":
    plot_error_and_accuracy_changing_noise_factor()
